name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      work-dir: ./MamasRezepte 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Print working directory
      run: pwd
      working-directory: ${{env.work-dir}}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.work-dir}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.work-dir}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.work-dir}}
    - name: Publish
      run: dotnet publish
      working-directory: ${{env.work-dir}}
