name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      work-dir: ./MamasRezepte 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Print working directory
      run: pwd
      working-directory: ${{env.work-dir}}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.work-dir}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.work-dir}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.work-dir}}
    - name: Publish
      run: dotnet publish
      working-directory: ${{env.work-dir}}
    -name: Upload Shared Build Artifact
     uses: actions/upload-artifact@v2
     with:
      name: MamasRezepte.Shared
      path: /home/runner/work/mamas_rezepte_blazor/mamas_rezepte_blazor/MamasRezepte/Shared/bin/Debug/netstandard2.1/publish/
    -name: Upload Client Build Artifact
     uses: actions/upload-artifact@v2
     with:
      name: MamasRezepte.Client
      path: /home/runner/work/mamas_rezepte_blazor/mamas_rezepte_blazor/MamasRezepte/Client/bin/Debug/netstandard2.1/publish/
    -name: Upload Server Build Artifact
     uses: actions/upload-artifact@v2
     with:
      name: MamasRezepte.Server
      path: /home/runner/work/mamas_rezepte_blazor/mamas_rezepte_blazor/MamasRezepte/Server/bin/Debug/netstandard2.1/publish/
