name: Publish to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and deploy the Docker image
        env: 
          HEROKU_USER_NAME: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        working-directory: ./MamasRezepte
        run: |
          docker login --username=$HEROKU_USER_NAME --password=$HEROKU_API_KEY registry.heroku.com
          heroku stack:set heroku-20
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
          
