name: Publish to Heroku

on:
  push:
    branches: [ main ]

jobs:
  publish_mamasrezepte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, push and deploy Docker image
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: './MamasRezepte'
